#! /bin/sh

#terminate script on failure
set -e

echo
echo Starting double
echo
cd Linux_Serial_Double
touch src/garbage
rm src/*
make
cd ..


echo
echo Starting Mixed
echo
cd Linux_Serial_Mixed
touch src/garbage
rm src/*
make
cd ..


echo
echo Starting Single
echo
cd Linux_Serial_Single
touch src/garbage
rm src/*
make
cd ..
