#! /bin/sh

cd /home/nslindquist/cs_research/Lindquist-Neil-Work/hpcg/

if [ $# != 0 ]; then
	sed 3s/.\*/$1\ $1\ $1/ -i MPI_Intel_OMP_Double/bin/hpcg.dat
	sed 3s/.\*/$1\ $1\ $1/ -i MPI_Intel_OMP_Mixed/bin/hpcg.dat
	sed 3s/.\*/$1\ $1\ $1/ -i MPI_Intel_OMP_Single/bin/hpcg.dat
fi


echo
echo ---starting double---
echo

cd MPI_Intel_OMP_Double/bin
/opt/intel-openmpi/bin/mpiexec xhpcg
cd ../..


#echo
#echo ---starting mixed---
#echo
#
#cd MPI_Intel_OMP_Mixed/bin
#/opt/intel-openmpi/bin/mpiexec xhpcg
#cd ../..


echo
echo ---starting single---
echo

cd MPI_Intel_OMP_Single/bin
/opt/intel-openmpi/bin/mpiexec xhpcg
cd ../..
